### ISSUE TITLE
Switch to Azure or Other Cloud Computing Program

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#104]
Since Heroku will stop being nice to us, we need to switch to Azure or something else.

- [glitch](https://glitch.com/)
- [porter.run](https://porter.run/)
- [render.com](http://render.com/)
- [back4app.com](http://back4app.com/)
- [adaptable.io](http://adaptable.io/)
- [render.com](http://render.com/)
- [dokku.com](http://dokku.com/)
- [fly.io](http://fly.io/)
- [railway](https://railway.app/)
- [deta.sh](https://www.deta.sh/)

https://blog.back4app.com/top-10-heroku-alternatives
https://www.makeuseof.com/heroku-alternatives-free-full-stack-hosting/

**Comment by OverlordsIII** [comment]
If you want, we can apply for the GH student thing for Heroku that will give us some credits to run the backend server.

**Comment by ronakkothari123** [comment]
Should be complete
