### ISSUE TITLE
Get Numerical Information

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#112]
Just a request that gets the number of signed up users.

**Comment by ronakkothari123** [comment]
It would be cool if there is a way of getting the number of flashcards made too

**Comment by OverlordsIII** [comment]
Is now done and seems to work.
![image](https://user-images.githubusercontent.com/69648849/215208516-2951f2e9-19e8-4ec7-932e-f5cb0b47825e.png)

**Comment by ronakkothari123** [comment]
By Flashcards created, I meant the amount of decks created. Cards is still good to keep, so maybe just add to it. Also add the amount of questions answered, if that is possible, as well as the number of questions asked. Actually lemme make checklist

- [ ] Number of Decks Created
- [ ] Number of Questions Asked
- [ ] Number of Questions Answered

**Comment by OverlordsIII** [comment]
Wait why wouldn't the questions asked be equal to the questions answered? If a question is being asked, then isn't it going to be answered?

**Comment by ronakkothari123** [comment]
Some questions aren't answered at the moment of being asked. This is just to display on the webpage

**Comment by OverlordsIII** [comment]
Whats the difference between questions asked and the number of flashcards?

**Comment by ronakkothari123** [comment]
Number of Flashcards has to do with Elephant Flip and number of questions asked has to do with Elephant Answers

**Comment by OverlordsIII** [comment]
ohhh this is related to elephant answers okay.

**Comment by OverlordsIII** [comment]
Should work now
![image](https://user-images.githubusercontent.com/69648849/215349421-cedada38-aa4d-494f-b25f-f63e6bd130bb.png)

**Comment by OverlordsIII** [comment]
oh wait i forgot to keep the card data, will do that now

**Comment by OverlordsIII** [comment]
![image](https://user-images.githubusercontent.com/69648849/215349562-87c095c6-5ead-44f9-b9ce-c8b0893f827e.png)

**Comment by ronakkothari123** [comment]
Coolio
