### ISSUE TITLE
Answers Description not really working.

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#114]
I think it would be better if the content for the answers (the description) is HTML instead of a string, as this would allow for more complicated questions to be asked.

**Comment by OverlordsIII** [comment]
the html should be generated on the client and can then be stored on the server as a string

**Comment by ronakkothari123** [comment]
![image](https://user-images.githubusercontent.com/70562508/215892270-be9e8ce1-7bc1-4f19-8624-2ea38694bd04.png)

**Comment by ronakkothari123** [comment]
![image](https://user-images.githubusercontent.com/70562508/215892603-7af89e75-6363-4341-a761-fa87ae52398e.png)
I figured out how to make it work, however, now there is this error and I'm currently crying.

**Comment by OverlordsIII** [comment]
this is massive cringe will fix

**Comment by OverlordsIII** [comment]
can u send me the request u made w the body and endpoint

**Comment by ronakkothari123** [comment]
![image](https://user-images.githubusercontent.com/70562508/215899261-ca3db021-8d55-4105-abd4-5cc1ce7aa996.png)

**Comment by ronakkothari123** [comment]
Let me know if you need help understanding my cringe

**Comment by OverlordsIII** [comment]
nah nah it looks fine for me to understand. Ima look at it tmrw

**Comment by OverlordsIII** [comment]
![image](https://user-images.githubusercontent.com/69648849/216111916-4bbb6e76-528f-4f8a-b48a-2823d82dd43d.png)

**Comment by ronakkothari123** [comment]
> can u send me the request u made w the body and endpoint

Let me take screenshot and show you :)

**Comment by OverlordsIII** [comment]
does it still happen for u? I can't reproduce the error

**Comment by OverlordsIII** [comment]
should also wor now

**Comment by OverlordsIII** [comment]
now t really wors
