### ISSUE TITLE
Literally Everything is Broken

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#119]
Everything is broken lol. There are few features that work but most of them end up with me in a pool of my own tears.
![image](https://user-images.githubusercontent.com/70562508/216360384-8c878537-437e-4276-9b9f-120f64a3cb1e.png)
^ this was when I tried to get numericalInformation. This caused me to shed exactly 2.75 tears (the middle tear was kinda smol).

I can't keep going like this. Please help.

**Comment by OverlordsIII** [comment]
should wor now
