### ISSUE TITLE
Sharing Notification Breaks... Everything

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#19]
Upon creating and sending a sharedDeck notification, the recipient's entire user object seems to break.

**Comment by OverlordsIII** [comment]
I'll figure it out when I get home

**Comment by ronakkothari123** [comment]
Wait where are you right now?

**Comment by OverlordsIII** [comment]
Office Depot

**Comment by OverlordsIII** [comment]
should be fixed now can you check later?

**Comment by ronakkothari123** [comment]
Checked, and it isn't fixed 😭

**Comment by OverlordsIII** [comment]
Should be fixed now, will merge

**Comment by OverlordsIII** [comment]
@ronakkothari123 can you check if this works now?

**Comment by ronakkothari123** [comment]
No longer breaking things
