### ISSUE TITLE
Storing Last Visited Deck

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#22]
My suggestion: Use a Stack data structure and add a limit of 50 before making the Stack remove older decks before adding new ones.

**Comment by OverlordsIII** [comment]
Rn this is there but it is only for 30 decks

**Comment by OverlordsIII** [comment]
oh wait I was using a list instead of a stack i can use that instead

**Comment by ronakkothari123** [comment]
No an ordinary list would work fine

**Comment by OverlordsIII** [comment]
nah it's fine a stack/deque is probably more appropriate

**Comment by OverlordsIII** [comment]
oh rip nvm you can't spring/hibernate doesnt let u

**Comment by OverlordsIII** [comment]
Can you check this as well @ronakkothari123?

**Comment by ronakkothari123** [comment]
Completed
