### ISSUE TITLE
Send Email to Confirm Account

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#38]
Right now, account confirmation is automatically done in Elephant Login

**Comment by OverlordsIII** [comment]
Things needed to fix this:
1. Need an html file that should be used for the email
2. An official elephant gmail account

**Comment by ronakkothari123** [comment]
Step 1 should be done.

**Comment by ronakkothari123** [comment]
Step 3 should work

**Comment by OverlordsIII** [comment]
Step 1 (the HTML file) seems to break when displayed in an email client or mail app.

**Comment by ronakkothari123** [comment]
Proposing a new image @OverlordsIII

**Comment by OverlordsIII** [comment]
what's the new image

**Comment by OverlordsIII** [comment]
send it on discord por favor

**Comment by ronakkothari123** [comment]
`HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm Email</title>

    <style>
        body{
            font-family: 'Montserrat', sans-serif;
            background:#f6f7fb;
            display:flex;
            flex-direction:row;
            align-items:flex-start;
            justify-content:center;
            margin:0;
        }

        img{
            width:600px;
        }
    </style>
</head>
<body>
    <a href=""><img src="./elephant-email.png" alt=""></a>
</body>
</html>
`

Image:
![elephant-email](https://user-images.githubusercontent.com/70562508/198899795-467018e4-f141-4710-add1-6028c353d956.png)

**Comment by ronakkothari123** [comment]
Has it been added to main?

**Comment by OverlordsIII** [comment]
ye but not been pushed to prod yet

**Comment by OverlordsIII** [comment]
since not all the other email stuff has been finished

**Comment by ronakkothari123** [comment]
Just letting you know that a lot of email related advancements have been made.
