### ISSUE TITLE
Ability to Send Notification More Than Once

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#65]
When sharing a deck with a person, you are able to send them more than one notification.
This should not be.

Also check if same can happen when friending.

**Comment by ronakkothari123** [comment]
oh no :(
![image](https://user-images.githubusercontent.com/70562508/188539504-9d67544a-23e6-4516-a0ff-901b5c370fdb.png)

**Comment by OverlordsIII** [comment]
forgot to merge

**Comment by ronakkothari123** [comment]
👍

**Comment by OverlordsIII** [comment]
wait one min and try again
