### ISSUE TITLE
Share Elephant Suite Email

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#82]
Allow users to send particular email addresses an email about Elephant. We should keep track of those who have been sent the email, so we don't spam them, but this is a good way for users to invite their friends over to elephant. I'll give you a mock email design later.

**Comment by OverlordsIII** [comment]
kk ill add it but gib mock email por favor

**Comment by OverlordsIII** [comment]
Closing this as it seems completed.
