### ISSUE TITLE
Elephant Admin Account

### ISSUE THREAD

**Issue by ronakkothari123** [Elephant-Learning/Elephant-Rearend#93]
Not sure if this is already there, but we need an Elephant Admin account type. This should only be able to be set within the Elephant Database thing in IntelliJ and it allows commands to be run. Pretty much if a command is run that requires admin, it will require the userID and it will check if that user is an admin, and only then will the command run. This is cool idea, right?

**Comment by Dhruv-0-Arora** [comment]
I agree with this idea, sounds great

**Comment by OverlordsIII** [comment]
This was there in the old commit but then i reverted
